name: Example workflow for Node using Snyk

on:
  push:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run Snyk to check for vulnerabilities
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  # Ensure your Snyk token is set as a GitHub secret

      # Optionally, monitor the project for new vulnerabilities
      - name: Monitor with Snyk
        uses: snyk/actions/node@master
        with:
          args: monitor  # This will upload your project's state to the Snyk dashboard
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Run Tests
      - name: Run Tests
        run: npm test

      # Deploy to Production (only if tests and security checks pass)
      - name: Deploy to Production
        if: success()  # This will only run if the previous steps were successful
        run: |
          echo "Deploying to production..."
          # Add actual deployment script here (e.g., AWS, DigitalOcean)
